[package]
name = "check_if_email_exists"
version = "0.1.1"
authors = ["Amaury Martiny <amaury.martiny@protonmail.com>"]
edition = "2018"

[lib]
path = "src/lib.rs"

[[bin]]
name = "check_if_email_exists"
path = "cli/src/main.rs"
doc = false

[[bin]]
name = "check_if_email_exists_serverless"
path = "serverless/src/main.rs"

[dependencies]
clap = { version = "2.32", features = ["yaml"] }
env_logger = "0.6"
lambda_http = "0.1"
lambda_runtime = "0.2"
lettre = { git = "https://github.com/lettre/lettre", rev = "1cbcbbb11f7a39a5d5d3829ce4162ca1beafedfb" }
log = "0.4"
native-tls = "^0.2"
rayon = "1.0.3"
serde_json = "1.0"
trust-dns-resolver = "0.10.2"
